ALTER TABLE users
  ADD COLUMN IF NOT EXISTS plan_slug      VARCHAR(20) NOT NULL DEFAULT 'pro',
  ADD COLUMN IF NOT EXISTS billing_cycle  VARCHAR(10) NOT NULL DEFAULT 'monthly',
  ADD COLUMN IF NOT EXISTS plan_renews_at DATE        NOT NULL DEFAULT (CURRENT_DATE + INTERVAL '30 days'),
  ADD COLUMN IF NOT EXISTS plan_cancelled BOOLEAN     NOT NULL DEFAULT FALSE;
